### ISSUE TITLE
an error occurred during the ploting process

### ISSUE THREAD

**Issue by MengXin001** [CyanideCN/SatimaV4#1]
Program error in polting satellite data(H8Target)
Using `Python3.8`and`matplotlib3.3.3`
```Task(band=13, georange=None, cmap='CA')
Traceback (most recent call last):
  File "Satima.py", line 151, in <module>
    Routine()
  File "Satima.py", line 43, in __init__
    self.plot()
  File "Satima.py", line 148, in plot
    plotter.plot()
  File "/home/pi/Desktop/SatimaV4/satima/plot.py", line 161, in plot
    self.plot_single_band(task)
  File "/home/pi/Desktop/SatimaV4/satima/plot.py", line 133, in plot_single_band
    self._plot(task)
  File "/home/pi/Desktop/SatimaV4/satima/plot.py", line 50, in _plot
    ax.background_patch.remove()
  File "/home/pi/.local/lib/python3.8/site-packages/matplotlib/artist.py", line 153, in remove
    raise NotImplementedError('cannot remove artist')
NotImplementedError: cannot remove artist
```

**Comment by CyanideCN** [comment]
cartopy的版本是多少啊
